trigger:
- main

pool:
  name: stud-sh-pool  # 👈 Your self-hosted Windows agent pool name

variables:
  phpVersion: 8.2
  packagePath: '$(Build.ArtifactStagingDirectory)\app.zip'

steps:
# ✅ Checkout code




# ✅ Archive Laravel app
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packagePath)'
    replaceExistingArchive: true
  displayName: 'Archive PHP App'

# ✅ Publish artifact to pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

# ✅ Deploy to Azure Linux App Service
- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy to Azure Linux App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(1)(8ca97cad-9ab1-42a2-9d9e-bdbf8876c147)'         # 👈 Update this
    appType: 'webAppLinux'                                      # 👈 IMPORTANT: must be Linux
    WebAppName: 'studdmsstatic'                           # 👈 Update this
    deployToSlotOrASE: true
    ResourceGroupName: 'rgp-devops'                 # 👈 Update this
    SlotName: 'production'
    packageForLinux: '$(packagePath)'                           # 👈 Use `packageForLinux` here
    RuntimeStack: 'PHP|8.2'                                     # 👈 Linux runtime (App Service Plan)
    StartupCommand: ''
    DeploymentTypeLinux: 'oneDeploy'
